export const smsResponsesTable = {
  401: 'Credentials Error, may be invalid username or password',
  402: 'X X messages submitted successfully',
  403: 'Credits not available',
  404: 'Internal Database Error',
  405: 'Internal Networking Error',
  406: 'Invalid or Duplicate numbers',
  407: 'Network Error on SMSC',
  408: 'Network Error on SMSC',
  409: 'SMSC response timed out, message will be submitted',
  410: 'Internal Limit Exceeded, Contact support',
  411: 'Sender ID not approved',
  412: 'Sender ID not approved',
  413: 'Suspect Spam, we do not accept these messages.',
  414: 'Rejected by various reasons by the operator such as DND, SPAM etc',
  415: 'Secure Key not available',
  416: 'Hash doesn’t match',
  418: 'Daily Limit Exceeded',
  498: 'Message already sent.',
  499: 'User with no phone number',
};
