name: "TestWorkflow"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: change directory
        run: cd packages/common
      - name: Run tests
        run: npm run test
        working-directory: packages/common